language: node_js
node_js:
  - "5.1"
  - "4.2"

notifications:
  email: false
  slack: we-are-sidekick:GeIT5wtuKMLImpFXYHWzIGzI

script:
  - npm test 
  - ./sidekick.js -v
  - echo If you are looking at this build config as an example of how to comfigure Sidekick on ci - be aware that the correct invocation is sidekick run --ci
  - DEBUG=* ./sidekick.js run .
